create database task11
use task11

--CREATE TABLE STUDENTS

CREATE TABLE STUDENTS(
S_ID INT,
S_NAME VARCHAR(20),
S_DEPT VARCHAR(20),
S_YEAR_COMPLETE INT
)

--INSERTING VALUES

INSERT INTO STUDENTS VALUES(1,'SHINCHAN','BBA',2023),
(2,'HATORI','BCA',2023),(3,'HARRY','BCA',2023),(4,'HEEMAVARI','BSC IT',2023),
(5,'TOYO','MBA',2023),(6,'JOOLY','CSC',2023),(7,'BEEMA','BBA',2023),
(8,'OSWOLD','BCA',2022),(9,'SHEERO','BSC IT',2022),(10,'JIAN','CSC',2022),
(11,'CAMOMACI','BA ENG',2022),(12,'GLORIA','BBA',2023),(13,'TOM','BBA',2023),
(14,'JERRY','BSC MATHS',2023),(15,'CHUTKI','MBA',2023),(16,'BHEEM','BBA',2023),
(17,'KALIA','BBA',2022),(18,'RAJU','BBA',2022),(19,'SONU','BBA',2023),
(20,'MONU','BCA',2023)

--RETRIEVING ROWS

SELECT * FROM STUDENTS

--1

--PIVOT
--IGNORE SPACES IN DEPARTMENT

SELECT S_YEAR_COMPLETE,BBA,BCA,CSC,BSCIT,BSCMATHS,BAENG,MBA
FROM (SELECT S_ID,S_DEPT,S_YEAR_COMPLETE FROM STUDENTS)AS P1
PIVOT
(
COUNT(S_ID) FOR S_DEPT IN (BBA,BCA,CSC,BSCIT,BSCMATHS,BAENG,MBA)
) AS PIVOT_STUDENTS

SELECT * FROM STUDENTS


--UNPIVOT

SELECT * FROM(
SELECT S_YEAR_COMPLETE,BBA,BCA,CSC,BSCIT,BSCMATHS,BAENG,MBA FROM
(SELECT  S_ID,S_DEPT,S_YEAR_COMPLETE FROM STUDENTS) AS P1
PIVOT
(
COUNT(S_ID) FOR S_DEPT IN (BBA,BCA,CSC,BSCIT,BSCMATHS,BAENG,MBA)
 )AS PIVOT_STUDENTS
 ) AS UP

 UNPIVOT
 (
 S_ID FOR S_DEPT IN  (BBA,BCA,CSC,BSCIT,BSCMATHS,BAENG,MBA)
 ) AS UNPIVOT_STUDENTS


 --NEW DATABASE

 CREATE DATABASE LIBRARY_MANAGEMENT

 USE LIBRARY_MANAGEMENT


 --CREATE TABLE LIBRARIAN

 CREATE TABLE LIBRARIAN(
 BOOK_ID INT PRIMARY KEY,
)

--INSERT VALUES

INSERT INTO LIBRARIAN VALUES(111),(102),(101),(190),(120)

--RETRIEVE VALUES

SELECT * FROM LIBRARIAN

--CREATE TABLE STUDENT

CREATE TABLE STUDENT(
STUDENT_NAME VARCHAR(20),
BOOK_NAME VARCHAR(20),
BOOK_ID INT REFERENCES LIBRARIAN(BOOK_ID)
)

--INSERT VALUES

INSERT INTO STUDENT VALUES('HARITA','HARRY PORTER',111),('RANITA','HARRY PORTER1',120),('HARISHMITHA','HARRY PORTER2',190),('YAMINI','HARRY PORTER3',102),('KAVYA','HARRY PORTER4',101)


--RETRIEVE VALUES

SELECT* FROM STUDENT
SELECT * FROM LIBRARIAN

ALTER TABLE STUDENT DROP [FK__STUDENT__BOOK_ID__37A5467C]

ALTER TABLE STUDENT DROP COLUMN BOOK_ID

ALTER TABLE STUDENT ADD BOOK_ID INT DEFAULT 120 CONSTRAINT FK_STU_BOOK_ID FOREIGN KEY(BOOK_ID) REFERENCES LIBRARIAN(BOOK_ID) ON DELETE CASCADE ON UPDATE SET DEFAULT 

UPDATE STUDENT SET BOOK_ID=101 WHERE BOOK_NAME='HARRY PORTER'
UPDATE STUDENT SET BOOK_ID=102 WHERE BOOK_NAME='HARRY PORTER1'
UPDATE STUDENT SET BOOK_ID=111 WHERE BOOK_NAME='HARRY PORTER2'
UPDATE STUDENT SET BOOK_ID=120 WHERE BOOK_NAME='HARRY PORTER3'
UPDATE STUDENT SET BOOK_ID=190 WHERE BOOK_NAME='HARRY PORTER4'

DELETE FROM LIBRARIAN WHERE BOOK_ID=101

UPDATE LIBRARIAN SET BOOK_ID=140 WHERE BOOK_ID=102