create database task16

use task16

--TABLE CREATION

CREATE TABLE TRIGGER_TABLE(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(20)
)

--INSERTING VALUES

INSERT INTO TRIGGER_TABLE(NAME) VALUES('HARITA'),('RANITA'),('SAVITHA'),('KAVITHA')

--RETRIEVING RECORDS

SELECT * FROM TRIGGER_TABLE

--1  Create a DML trigger to restrict DML operations on Saturday and Sunday.

ALTER TRIGGER
TRIGGEROPERATIONSRESTRICT

ON TRIGGER_TABLE

FOR INSERT, UPDATE, DELETE

AS

BEGIN

  IF DATEPART(DW,GETDATE())= 7
  BEGIN
    PRINT 'DML OPERATIONS ARE RESTRICTED ON SATURDAY'
	 ROLLBACK TRANSACTION
	END

	ELSE IF(DATEPART(DW,GETDATE())= 1)
	BEGIN
	PRINT 'DML OPERATIONS ARE RESTRICTED ON SUNDAY'
	ROLLBACK TRANSACTION
	END

	ELSE
	BEGIN
	PRINT 'NO COMMENTS'
	END

	END
   
 INSERT INTO TRIGGER_TABLE(NAME) VALUES('HARISH')

 UPDATE TRIGGER_TABLE SET NAME='KAVYA' WHERE ID=3

 DELETE FROM TRIGGER_TABLE WHERE ID=2

 SELECT * FROM TRIGGER_TABLE


 --2

 --Create a DML trigger to restrict delete operations between 11:00AM to 15:00PM.

 ALTER TRIGGER TRIGGER_OPERATION_DELETE
ON TRIGGER_TABLE
FOR DELETE
AS
BEGIN

  IF DATEPART(HH,GETDATE()) > 11 AND DATEPART(HH,GETDATE()) < 15
   BEGIN
   PRINT 'DML OPERATIONS ARE RESTRICTED BETWEEN 11:00 TO 15:00PM'
   ROLLBACK TRANSACTION
   END

	END

--FOR CHECKING IT IS RESTRICTED OR NOT

 DELETE FROM TRIGGER_TABLE WHERE ID=4

 --RETRIVING ROWS

 SELECT * FROM TRIGGER_TABLE


 --3

--Create a DDL trigger to show notification whenever a CREATE, ALTER, DROP, RENAME operation is performed.

CREATE TRIGGER DDL_TRIGGER_PERFORMED
ON DATABASE 
FOR CREATE_TABLE,ALTER_TABLE,DROP_TABLE,RENAME
AS
BEGIN
PRINT 'DDL OPERATIONS ARE PERFORMED'
END

--CHECKING

CREATE TABLE DDL_EXAMPLE_TRIGGER(
NAME VARCHAR(20)
)

ALTER TABLE DDL_EXAMPLE_TRIGGER ADD ADDRESS VARCHAR(20)

ALTER TABLE DDL_EXAMPLE_TRIGGER ADD STATE VARCHAR(9)

sp_rename 'DDL_EXAMPLE_TRIGGER', 'DDL_EXAMPLE_TRIGGER_DDL'

DROP TABLE DDL_EXAMPLE_TRIGGER_DDL







